[package]
name = "lswtss-open-modding-platform-driver-dinput8-library"
version = "1.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
winapi = { version = "^0.3.0", features = [
  "libloaderapi",
  "minwindef",
  "sysinfoapi",
  "winnt",
] }
