[package]
name = "lswtss-open-modding-platform-foundation"
version = "1.0.0"
edition = "2018"

[dependencies]
schemars = "^0.8.0"
serde = "^1.0.0"
serde_json = "^1.0.0"
uuid = { version = "^1.0.0", features = ["v5"] }
